import React from "react";
import Link from "next/link";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SIGNIN
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/checkout" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Checkout
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/signup" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SIGNUP
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/productlist" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Productlist
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/shoppingcart" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ShoppingCart
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
